apiVersion: v1
kind: ConfigMap
metadata:
  name: scion-broker-kubeconfig
  labels:
    app.kubernetes.io/name: scion-hub
    app.kubernetes.io/component: broker
    app.kubernetes.io/part-of: scion-control-plane
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: in-cluster
        cluster:
          server: https://kubernetes.default.svc
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
      - name: scion-control-plane
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
      - name: in-cluster
        context:
          cluster: in-cluster
          user: scion-control-plane
          namespace: scion-agents
    current-context: in-cluster
