apiVersion: v1
kind: ServiceAccount
metadata:
  name: scion-control-plane
  labels:
    app.kubernetes.io/name: scion-hub
    app.kubernetes.io/component: broker
    app.kubernetes.io/part-of: scion-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scion-control-plane-broker
  labels:
    app.kubernetes.io/name: scion-hub
    app.kubernetes.io/component: broker
    app.kubernetes.io/part-of: scion-control-plane
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "list", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scion-control-plane-broker
  labels:
    app.kubernetes.io/name: scion-hub
    app.kubernetes.io/component: broker
    app.kubernetes.io/part-of: scion-control-plane
subjects:
  - kind: ServiceAccount
    name: scion-control-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scion-control-plane-broker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scion-control-plane-broker-namespaces
  labels:
    app.kubernetes.io/name: scion-hub
    app.kubernetes.io/component: broker
    app.kubernetes.io/part-of: scion-control-plane
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scion-control-plane-broker-namespaces
  labels:
    app.kubernetes.io/name: scion-hub
    app.kubernetes.io/component: broker
    app.kubernetes.io/part-of: scion-control-plane
subjects:
  - kind: ServiceAccount
    name: scion-control-plane
    namespace: scion-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scion-control-plane-broker-namespaces
