apiVersion: v1
kind: ConfigMap
metadata:
  name: scion-hub-settings
  labels:
    app.kubernetes.io/name: scion-hub
    app.kubernetes.io/component: hub
    app.kubernetes.io/part-of: scion-control-plane
data:
  settings.yaml: |
    schema_version: "1"
    image_registry: localhost
