apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scion-hub-state
  labels:
    app.kubernetes.io/name: scion-hub
    app.kubernetes.io/component: hub
    app.kubernetes.io/part-of: scion-control-plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
