apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scion-agents
resources:
  - broker-rbac.yaml
  - broker-pvc.yaml
  - broker-deployment.yaml
  - mcp-rbac.yaml
  - web-rbac.yaml
  - hub-pvc.yaml
  - hub-service.yaml
  - hub-deployment.yaml
  - mcp-checkouts-pvc.yaml
  - mcp-service.yaml
  - mcp-deployment.yaml
  - web-service.yaml
  - web-deployment.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: scion-control-plane

configMapGenerator:
  - name: scion-broker-kubeconfig
    files:
      - config=config/broker-kubeconfig.yaml
  - name: scion-broker-entrypoint
    files:
      - broker-entrypoint.sh=config/broker-entrypoint.sh
  - name: scion-broker-bootstrap-server
    files:
      - server.yaml=config/broker-bootstrap-server.yaml
  - name: scion-broker-bootstrap-settings
    files:
      - settings.yaml=config/broker-bootstrap-settings.yaml
  - name: scion-hub-settings
    files:
      - settings.yaml=config/hub-settings.yaml
