apiVersion: v1
kind: Service
metadata:
  name: scion-ops-web-app
  labels:
    app.kubernetes.io/name: scion-ops-web-app
    app.kubernetes.io/component: web-app
    app.kubernetes.io/part-of: scion-control-plane
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: scion-ops-web-app
    app.kubernetes.io/component: web-app
  ports:
    - name: http
      port: 8787
      targetPort: http
      nodePort: 30877
